// SPDX-License-Identifier: MPL-2.0 · Copyright (c) Aurelian-Risk
// The engine's own words, per language.
//
// Text that belongs to THIS layer and not to any product: the completeness checks, the
// buttons, the dialogs, the messages. It looks like product text on screen, which is why
// it needs saying: `lint.ts` declares 21 checks with an English title and hint, and they
// describe the engine's own modelling. A product that does not switch them off gets them
// unasked.
//
// Without this file each product would translate the same 42 strings into its own table —
// 84 entries for 42 texts across two products, drifting apart the moment one of them
// fixes a typo, and under the lookup rule a wrong translation does not fail, it simply
// shows. The fork spotted that before writing them; this is where they go instead.
//
// Registered BEFORE a product's own table, so a product can still override any key it
// disagrees with. It does not decide which languages are on offer — that stays with the
// product, which knows what it ships.
//
// Empty while the engine is authored in English: a key nothing answers already shows
// English. It fills up when a second language is written.
import { LLM } from "./gen";
import type { Overlay } from "./i18n";

/** Words that only exist in the build that carries a language model.
 *
 *  They live behind the same build-time gate as the branch they describe, and for the same
 *  reason: a table is data, so a translation of "Smart engine · Language model" sits in the
 *  bundle whether or not the branch does. It did — the released file carried a line about a
 *  model it cannot run, which is exactly what `gen.ts` warns about and what the release
 *  script refuses to publish. `LLM` folds to a constant, so this object folds away with it. */
const GEN_WORDS_DE: Overlay = LLM ? {
  "ui.model.smart-engine-language-model": "Smart engine · Language model",
  "ui.model.reads-free-form-prose": "Liest freien Fließtext und gibt strukturierte Entitäten aus — am besten bei erzählenden Dokumenten. Groß (~0,25–2,2 GB); WebGPU empfohlen; läuft in einem Hintergrund-Worker.",
  "ui.model.qwen-webllm": "Qwen (WebLLM)",
  "ui.model.smollm": "SmolLM2",
  "ui.model.delete-cached-language-model": "Zwischengespeicherte Language-Model-Dateien aus diesem Browser löschen (behebt einen vollen oder beschädigten Cache)",
  "ui.model.server-address": "Serveradresse",
  "ui.extraction.a-local-language-model": "Ein lokales Language Model liest Fließtext und gibt strukturierte Entitäten aus.",
} : {};

export const ENGINE_WORDS: Record<string, Overlay> = {
  // German. What stays English is narrow and each case has a reason: the method's own
  // name (EBIOS RM), terms the German literature uses untranslated (kill chain, TTP,
  // Compliance, Monte-Carlo, Embeddings), product and model names, and words German
  // spells the same way (Format, Details, Navigation, Status, Graph, Import, Export).
  // Everything else is German, including the words this file kept in English until
  // 2026-08-31 — Taxonomie, Bericht, Modell, Ablauf, Risikomatrix, Restrisiko. A reader
  // who asks for German gets German; a term of art is not a reason to leave a screen
  // half-translated.
  de: {
    ...GEN_WORDS_DE,
    // ── shell ──
    "ui.app.loading": "Lädt …",
    "ui.nav.section": "Navigation",
    "ui.nav.studies": "Studien",
    "ui.nav.documents": "Dokumente",
    "ui.nav.documents.hasStudy": "Dokumente der aktiven Studie",
    "ui.nav.documents.none": "Dokumentkorpus importieren (legt eine Studie an)",
    "ui.nav.model": "Modell",
    "ui.nav.taxonomy": "Taxonomie",
    "ui.nav.timeline": "Verlauf",
    "ui.nav.timeline.title": "Änderungsverlauf der aktiven Studie",
    "ui.nav.theme.dark": "Dunkles Thema",
    "ui.nav.theme.light": "Helles Thema",
    // The button itself is NOT translated - it names the language it switches to, in that
    // language. Only what it does needs saying in the one being read.
    "ui.nav.language.title": "Die Oberfläche in einer anderen Sprache anzeigen",

    // ── studies ──
    "ui.dashboard.risk-studies": "Risikostudien",
    "ui.dashboard.new-study": "Neue Studie",
    "ui.dashboard.no-studies-yet": "Noch keine Studien",
    "ui.dashboard.create-your-first": "Legen Sie Ihre erste EBIOS-RM-Analyse an, laden Sie das Beispiel, oder importieren Sie eine {0}- / {1}-Datei.",
    "ui.dashboard.load-sample-study": "Beispielstudie laden",
    "ui.dashboard.study-name": "Name der Studie",
    "ui.dashboard.organization": "Organisation",
    "ui.dashboard.sector": "Branche",
    "ui.dashboard.not-set-no-sector": "Nicht gesetzt — keine Branchenanpassung",
    "ui.dashboard.some-kinds-of-attacker": "Manche Angreifer suchen sich bestimmte Branchen weit gezielter aus als andere. Wird von den Basisraten der Quantifizierung benutzt; später in der Calibration änderbar.",
    "ui.dashboard.analysis-perimeter-scope": "Betrachtungsbereich / Geltungsbereich",
    "ui.dashboard.what-is-in-scope": "Was gehört dazu? Welche Systeme, Prozesse, Grenzen?",
    "ui.dashboard.create": "Anlegen",
    "ui.dashboard.cancel": "Abbrechen",
    "ui.dashboard.delete": "Löschen",
    "ui.dashboard.reset": "Zurücksetzen",
    "ui.dashboard.clear-all-locally-stored": "Alle lokal gespeicherten Daten löschen und neu laden",

    // ── the workshop shell ──
    "ui.study.checks": "Prüfungen",
    "ui.study.analysis-completeness-checks": "Vollständigkeitsprüfungen der Analyse",
    "ui.study.flow": "Ablauf",
    "ui.study.graph": "Graph",
    "ui.study.report": "Bericht",
    "ui.study.relationships": "Beziehungen",
    "ui.study.event-chains": "Ereignisketten",
    "ui.study.generate-a-report-of": "Einen Report dieser Studie erzeugen",
    "ui.study.download-markdown": "Markdown herunterladen",
    "ui.study.open-in-browser-html": "Im Browser öffnen (HTML)",
    "ui.study.copy-this-workshop-as": "Diesen Workshop als LLM-tauglichen Kontext kopieren",

    // ── tables and records ──
    "ui.entitysection.edit": "Bearbeiten",
    "ui.entitysection.delete": "Löschen",
    "ui.entitysection.cancel": "Abbrechen",
    "ui.entitysection.open": "Öffnen",
    "ui.entitysection.view": "Ansehen →",
    "ui.entitysection.details": "Details",
    "ui.entitysection.referenced-by": "Verwiesen von",
    "ui.entitysection.change-history": "Änderungsverlauf",
    "ui.entitysection.extracted-from-this-source": "Aus dieser Quelle extrahiert",
    "ui.entitysection.clear-filters": "Filter zurücksetzen",
    "ui.entitysection.nothing-matches": "Nichts passt.",
    "ui.entitysection.nothing-else-is-affected": "Sonst ist nichts betroffen.",
    "ui.entitysection.nothing-else-is-deleted": "Sonst wird nichts gelöscht.",
    "ui.entitysection.counts-again-everywhere": "Zählt überall wieder mit.",
    "ui.entitysection.a-type-involved-has": "Ein beteiligter Typ hat in dieser Taxonomy keinen Schalter.",
    "ui.entitysection.to-keep-the-record": "Um den Datensatz mitsamt seiner Bewertung aus den Zahlen herauszuhalten, setzen Sie ihn stattdessen zurück.",

    "ui.entity.editor": "Bearbeiter",
    "ui.entity.change-note": "Änderungsnotiz",
    "ui.entity.referenced-by": "Verwiesen von",
    "ui.entity.extracted-from-this-source": "Aus dieser Quelle extrahiert",
    "ui.entity.open": "Öffnen",
    "ui.entity.back": "Zurück",
    "ui.entity.close": "Schließen",
    "ui.entity.cancel": "Abbrechen",
    "ui.entity.delete": "Löschen",

    "ui.entityinfo.edit": "Bearbeiten",
    "ui.entityinfo.close": "Schließen",
    "ui.entityinfo.relationships": "Beziehungen",

    "ui.tabletools.group-by": "Gruppieren nach",
    "ui.tabletools.group-the-rows-by": "Die Zeilen nach einer Spalte gruppieren",
    "ui.tabletools.which-columns-this-table": "Welche Spalten diese Tabelle zeigt",
    "ui.tabletools.clear-every-filter": "Alle Filter zurücksetzen",

    // ── history and checks ──
    "ui.changehistory.close": "Schließen",
    "ui.changehistory.no-changes-recorded-yet": "Noch keine Änderungen aufgezeichnet.",
    "ui.timeline.change-timeline": "Änderungsverlauf",
    "ui.timeline.no-active-study-open": "Keine aktive Studie. Öffnen Sie eine Studie, um ihren Änderungsverlauf zu sehen.",
    "ui.timeline.no-changes-recorded-yet": "Noch keine Änderungen aufgezeichnet. Bearbeiten Sie eine Entität (mit Bearbeitername und optionaler Notiz), dann erscheint sie hier.",
    "ui.completeness.quality-checks": "Qualitätsprüfungen",
    "ui.completeness.completeness-gaps-in-the": "Lücken in der Vollständigkeit der Analyse, mit den betroffenen Einträgen und dem Weg, sie zu schließen. Alles hier ist aus der Studie abgeleitet — beheben Sie es an der Quelle.",

    // ── data in and out ──
    "ui.datamenu.import-data": "Daten importieren…",
    "ui.datamenu.format": "Format",
    "ui.datamenu.taxonomy": "Taxonomie",
    "ui.datamenu.portable-session": "Portable Sitzung",
    "ui.datamenu.protection": "Schutz",
    "ui.datamenu.none": "Keiner",
    "ui.datamenu.password": "Passwort",
    "ui.datamenu.password-aes": "Passwort (AES-256)",
    "ui.datamenu.key": "Schlüssel",

    // ── documents ──
    "ui.documents.documents": "Dokumente",
    "ui.documents.reference-library": "Referenzbibliothek",
    "ui.documents.references": "Referenzen",
    "ui.documents.no-references-yet": "Noch keine Referenzen",
    "ui.documents.add-a-reference-to": "Fügen Sie eine Referenz auf ein Quelldokument hinzu, um Ihre Bibliothek zu beginnen.",
    "ui.documents.add-reference": "Referenz hinzufügen",
    "ui.documents.add-document": "Dokument hinzufügen…",
    "ui.documents.add-word-pdf-or": "Word-, PDF- oder Textdateien hinzufügen (der Text wird lokal extrahiert, vollständig offline). Das erste Dokument legt eine neue Studie an, die den Korpus hält.",
    "ui.documents.import-a-document-corpus": "Dokumentkorpus importieren",
    "ui.documents.import-framework": "Framework importieren",
    "ui.documents.import-a-requirement-measure": "Ein Requirement-/Measure-Framework aus einer Tabelle importieren (CSV/TSV/JSON)",
    "ui.documents.extract": "Extrahieren",
    "ui.documents.added": "Hinzugefügt",
    "ui.documents.name": "Name",
    "ui.documents.type": "Typ",
    "ui.documents.size": "Größe",
    "ui.documents.remove": "Entfernen",

    // ── extraction ──
    "ui.extraction.extract-entities": "Entitäten extrahieren",
    "ui.extraction.engine": "Verfahren",
    "ui.extraction.fast-engine": "Schnelles Verfahren.",
    "ui.extraction.embeddings-classify-sentences-into": "Embeddings ordnen Sätze der Taxonomy zu — am besten bei strukturierten, listenartigen Dokumenten.",
    "ui.extraction.model": "Modell",
    "ui.extraction.models-are-managed-in": "Models werden verwaltet im",
    "ui.extraction.no-extraction-model-is": "Es ist kein Extraktions-Model geladen.",
    "ui.extraction.document-name": "Name des Dokuments",
    "ui.extraction.text": "Text",
    "ui.extraction.open-file": "Datei öffnen",
    "ui.extraction.paste-document-text-or": "Dokumenttext einfügen, oder „Datei öffnen“ benutzen (der Inhalt wird nur flüchtig gelesen, nicht gespeichert)…",
    "ui.extraction.no-candidates-found": "Keine Kandidaten gefunden.",
    "ui.extraction.best-and-second-best": "Bester und zweitbester Typ lagen dicht beieinander — bitte prüfen",
    "ui.extraction.the-passage-could-not": "Die Stelle war im aktuellen Text nicht auffindbar — er wurde womöglich seit der Extraktion bearbeitet.",
    "ui.extraction.stop": "Anhalten",
    "ui.extraction.cancel": "Abbrechen",
    "ui.extraction.close": "Schließen",

    // ── models ──
    "ui.model.models": "Modelle",
    "ui.model.ai-offline": "KI · offline",
    "ui.model.two-independent-engines-load": "Zwei unabhängige Engines — laden Sie eine oder beide. Alles läuft lokal in Ihrem Browser.",
    "ui.model.fast-engine-embeddings": "Schnelles Verfahren · Embeddings",
    "ui.model.classifies-sentences-into-the": "Ordnet Sätze der Taxonomy zu — am besten bei strukturierten, listenartigen Dokumenten. Klein (~25–34 MB).",
    "ui.model.download-amp-load": "Herunterladen &amp; laden",
    "ui.model.use-file": "Datei benutzen…",
    "ui.model.pick-an-existing-aurelian": "Eine vorhandene aurelian-model.bin wählen — wird ohne Download wiederverwendet (funktioniert auch auf file://)",
    "ui.model.save-file": "Datei speichern",
    "ui.model.the": "Das",
    "ui.model.look-again": "Erneut suchen",
    "ui.model.add-model": "Model hinzufügen…",
    "ui.model.label": "Bezeichnung",
    "ui.model.note": "Notiz",
    "ui.model.size": "Größe",
    "ui.model.add": "Hinzufügen",
    "ui.model.cancel": "Abbrechen",
    "ui.model.clear": "Leeren",
    "ui.model.remove-this-model": "Dieses Model entfernen",

    // ── seals and keys ──
    "ui.seal.seals": "Siegel",
    "ui.seal.seal": "Siegel",
    "ui.seal.seal-this-study": "Diese Studie versiegeln",
    "ui.seal.seal-as": "Versiegeln als",
    "ui.seal.sealed-by": "Versiegelt von",
    "ui.seal.not-sealed-a-seal": "Nicht versiegelt. Ein Seal signiert das bisherige Änderungsprotokoll, sodass jede Änderung an bereits Aufgezeichnetem den privaten Schlüssel erfordert.",
    "ui.seal.the-signature-covers-the": "Die Signatur deckt den Kopf des Änderungsprotokolls ab, also ist jeder vor dem Seal aufgezeichnete Eintrag genau das, was signiert wurde. Etwas davon zu ändern erfordert den Schlüssel.",
    "ui.seal.the-log-itself-does": "Das Protokoll selbst verifiziert nicht, ein Seal kann also nur für das sprechen, was vor dem Bruch liegt.",
    "ui.seal.this-browser-exposes-no": "Dieser Browser bietet keine Web Crypto, hier lassen sich Studien nicht versiegeln.",
    "ui.seal.what-does-a-seal": "Was beweist ein Seal?",
    "ui.seal.what-a-seal-proves": "Was ein Seal beweist",
    "ui.seal.it-proves-the-history": "Es beweist die Historie.",
    "ui.seal.it-makes-its-author": "Es macht seinen Urheber dafür verantwortlich.",
    "ui.seal.it-does-not-prove": "Es beweist nicht, wann.",
    "ui.seal.a-signature-carries-no": "Eine Signatur trägt keine Zeit; wer den Schlüssel hat, kann ein Seal datieren, wie er will.",
    "ui.seal.it-does-not-prove-2": "Es beweist für sich genommen nicht, wer.",
    "ui.seal.it-proves-the-holder": "Es beweist „der Inhaber dieses Schlüssels“. Vergleichen Sie den Fingerabdruck auf einem anderen Weg und benennen Sie dann den Schlüssel — danach lesen sich Seals von ihm als verifiziert.",
    "ui.seal.it-does-not-make": "Es macht den Inhalt nicht wahr.",
    "ui.seal.anyone-can-check-a": "Jeder kann ein Seal ohne diese Anwendung prüfen: es ist ein JWS (ES256), und der öffentliche Schlüssel reist mit.",
    "ui.seal.keys": "Schlüssel",
    "ui.seal.keys-you-have-named": "Schlüssel, die Sie benannt haben",
    "ui.seal.none-yet-name-a": "Noch keine. Benennen Sie einen Schlüssel aus einem Seal, oder laden Sie die Datei mit dem öffentlichen Schlüssel einer anderen Person.",
    "ui.seal.this-installation": "Diese Installation",
    "ui.seal.create-a-key": "Schlüssel erzeugen",
    "ui.seal.private-key": "Privater Schlüssel",
    "ui.seal.public-key": "Öffentlicher Schlüssel",
    "ui.seal.save-private-key": "Privaten Schlüssel speichern…",
    "ui.seal.save-public-key": "Öffentlichen Schlüssel speichern…",
    "ui.seal.load-private-key": "Privaten Schlüssel laden…",
    "ui.seal.or-load-one": "Oder einen laden, den Sie schon haben {0}",
    "ui.seal.the-password-its-file": "das Passwort, mit dem die Datei gespeichert wurde",
    "ui.seal.add-someone-s-public": "Öffentlichen Schlüssel einer anderen Person hinzufügen…",
    "ui.seal.whose-key-is-it": "Wessen Schlüssel ist es?",
    "ui.seal.compare-this-fingerprint-with": "Vergleichen Sie diesen Fingerabdruck mit dem, den sein Inhaber Ihnen genannt hat — telefonisch, persönlich, auf jedem Weg außer der Datei selbst. Ihn hier zu benennen heißt, dass Sie das getan haben.",
    "ui.seal.it-is-theirs": "Er gehört ihm",
    "ui.seal.name-this-key": "Diesen Schlüssel benennen",
    "ui.seal.name-it": "Benennen…",
    "ui.seal.forget-this-key": "Diesen Schlüssel vergessen",
    "ui.seal.cancel": "Abbrechen",
    "ui.seal.close": "Schließen",

    // ── quantification ──

    // ── where a number comes from ──

    // ── calibration ──

    // ── sector ──
    "ui.sectorsection.sector": "Branche",
    "ui.sectorsection.not-set": "Nicht gesetzt",
    "ui.sectorsection.applied-to-the-attack": "Auf die Angriffsrate angewandt:",
    "ui.sectorsection.without-a-sector-the": "Ohne Branche benutzt die Quantification die veröffentlichten Basisraten unverändert. Eine zu wählen ändert die Angriffsrate nur dort, wo eine dokumentierte Abweichung vorliegt.",

    // ── charts and views ──
    "ui.assetheatmap.asset-criticality": "Kritikalität der Assets",
    "ui.assetheatmap.your-business-assets-ranked": "Ihre Business assets nach Kritikalität geordnet (das kritischste zuerst). Ein Klick auf eine Kachel zeigt die Supporting assets, von denen sie abhängt — damit Sie dem folgen können, was wirklich trägt.",
    "ui.assetheatmap.open": "Öffnen",
    "ui.attackpaths.attack-paths": "Angriffspfade",
    "ui.attackpaths.chains": "Ketten",
    "ui.attackpaths.choke-points": "Engstellen",
    "ui.attackpaths.target-assets": "Zielobjekte",
    "ui.attackpaths.no-kill-chain-steps": "Noch keine Kill-chain-Schritte — modellieren Sie die Kill chain eines Operational scenario, um seine Attack paths zu sehen.",
    "ui.attackpaths.toggle-a-scenario-above": "Schalten Sie oben ein Szenario ein, um seinen Attack path zu zeigen, und fügen Sie weitere hinzu, um zu sehen, wo sie zusammenlaufen.",
    "ui.canvas.back-to-the-wheel": "Zurück auf 100 % — das Rad zoomt, Ziehen des Hintergrunds verschiebt",
    "ui.canvas.click-a-node-to": "Klicken Sie einen Knoten an, um seine Ketten zu verfolgen — mehrere wählen verengt viele Pfade auf einen.",
    "ui.coveragematrix.coverage": "Abdeckung",
    "ui.coveragematrix.coverage-amp-traceability": "Coverage &amp; Nachvollziehbarkeit",
    "ui.coveragematrix.framework": "Rahmenwerk",
    "ui.coveragematrix.gaps-only": "Nur Lücken",
    "ui.coveragematrix.only-the-requirements-no": "Nur die Requirements, die keine Maßnahme erfüllt",
    "ui.coveragematrix.no-requirements-yet-add": "Noch keine Requirements — fügen Sie sie in der Requirements-Tabelle oben hinzu (etwa „+ From framework…“).",
    "ui.frameworkradar.framework-coverage": "Framework-Coverage",
    "ui.threatactorradar.threat-landscape": "Bedrohungslage",
    "ui.radarchart.not-enough-data-yet": "Noch nicht genug Daten.",
    "ui.riskmatrix.risk-matrix": "Risikomatrix",
    "ui.riskmatrix.inherent": "Inhärent",
    "ui.riskmatrix.residual": "Restrisiko",
    "ui.riskmatrix.reduce": "Reduzieren",
    "ui.riskmatrix.share": "Teilen",
    "ui.riskmatrix.accept": "Akzeptieren",
    "ui.riskmatrix.avoid": "Vermeiden",
    "ui.riskmatrix.hover-a-chip": "Für die Verschiebung mit dem Zeiger auf einen Chip gehen.",
    "ui.riskmatrix.residual-explained": "Restrisiko = Lage nach der Behandlung, {0} aus der Entscheidung und daraus, wie gut die Kill chain des Risikos gemindert ist: {1} senkt die Likelihood (um diese Coverage), {2} senkt die Gravity, {3} lässt sie stehen, {4} entfernt sie. Unbehandelte Risiken bleiben beim Inherent-Wert.",

    // ── added 2026-08-31, when the screen was measured against a German browser ──
    "ui.mitigation.gates-of-steps.one": "{0} von {1} Schritten hält einen Angreifer auf",
    "ui.mitigation.gates-of-steps.many": "{0} von {1} Schritten halten einen Angreifer auf",
    "ui.mitigation.steps-detect.one": "{0} erkennt ihn",
    "ui.mitigation.steps-detect.many": "{0} erkennen ihn",
    "ui.model.file-why": "Das Modell wird als Datei ({0}) abgelegt, damit eine {1}-Sitzung es nicht erneut herunterlädt.",
    "ui.model.file-step-1": "{0} — es öffnet sich ein Speichern-Dialog.",
    "ui.model.file-step-2": "Die Datei neben diese HTML-Datei legen.",
    "ui.model.file-step-3": "Beim nächsten Mal {0} wählen — es wird nichts heruntergeladen.",
    "ui.model.file-auto": "Schritt 2 und 3 funktionieren in Chrome und Edge. Unter {0} und in Firefox wird die Datei beim Start von selbst gefunden.",
    "ui.documents.references-for-study.one": "{0} Referenz für diese Studie · Word / PDF / Text - lokal extrahiert und zwischengespeichert",
    "ui.documents.references-for-study.many": "{0} Referenzen für diese Studie · Word / PDF / Text - lokal extrahiert und zwischengespeichert",
    "ui.attackpaths.choke-points-explained": "{0} sind Objekte, die mehr als eine Kill-Chain durchlaufen muss, um ihr Ziel zu erreichen. Weil dort mehrere Angriffspfade zusammenlaufen, mindert eine einzelne Maßnahme an dieser Stelle gleich mehrere Szenarien — das macht sie zur wirksamsten Investition. Szenarien einzeln zuschalten, um das Bild aufzubauen; einen Knoten anklicken, um den zugehörigen Schritt oder das Objekt zu öffnen.",
    "ui.mitigation.bar-counts-explained": "Der Balken zählt nur Maßnahmen, die einen Angreifer {0} aufhalten: präventive blockieren ihn, detektivische fassen ihn. Die übrigen bekommen keinen Balken, weil sie auf einen anderen Faktor wirken — {1} (Schadensbegrenzung: was der Angriff kostet, wenn er gelingt), {2}. Beide bewegen die Risikozahlen; keine ändert, ob dieser Schritt erreicht wird.",
    "ui.mitigation.at-this-step": "an diesem Schritt",
    "ui.mitigation.corrective-act-on-loss": "korrektive Maßnahmen wirken auf den Schaden",
    "ui.mitigation.deterrent-act-on-attacks": "abschreckende und vermeidende Maßnahmen wirken auf die Zahl der Angriffe",
    "ui.documents.guide": "Referenzen behalten Name, Art und Größe des Quelldokuments. Bei {0} wird zusätzlich der reine Text lokal zwischengespeichert (offline, in Ihrem Browser), damit {1} ihn sofort lesen kann — nichts wird hochgeladen. Für Entitätsvorschläge zur aktiven Studie {2} an einer Referenz anklicken.",
    "ui.documents.text-files": "Textdateien",
    "ui.assetheatmap.depend-on-this.one": "{0} hängt von diesem Wert ab",
    "ui.assetheatmap.depend-on-this.many": "{0} hängen von diesem Wert ab",
    "ui.graph.shift-click-to-add": "Mit Umschalt-Klick zum Fokus hinzufügen",
    "ui.graph.click-to-inspect": "· klicken zum Ansehen · Doppelklick zum Zentrieren · Umschalt-Klick zum Vergleichen",
    "ui.attackpaths.projection": "Nur-Lese-Projektion aller Kill-Chains auf die Zielobjekte",
    "ui.attackpaths.step-mitigated": "Schritt gemindert",
    "ui.attackpaths.coverage-gap": "Lücke in der Abdeckung",
    "ui.attackpaths.kill-chain-link": "Kill-Chain-Kante",
    "ui.attackpaths.cross-chain-link": "kettenübergreifende Kante",
    "ui.attackpaths.reaches-asset": "erreicht Objekt",
    "ui.sector.selects-the-exceptions": "wählt die Ausnahmen der Angriffsrate für diese Studie",
    "ui.killchainlane.drag-steps": "Schritte aus der Tabelle oder zwischen Kacheln ziehen →",
    "ui.frameworkradar.requirements-per-framework": "erfüllte Anforderungen je Rahmenwerk",
    "ui.killchainmitigation.expand-a-scenario": "Ein Szenario aufklappen, um den Schritten Maßnahmen zuzuordnen",
    "ui.effect.preventive": "blockiert den Angreifer an dem Schritt, den sie abdeckt - er muss sie überwinden, um weiterzukommen",
    "ui.effect.detective": "erkennt den Einbruch: vor dem Ziel kann sie die Kette unterbrechen, am Ziel verkürzt sie nur das Ereignis",
    "ui.effect.corrective": "Schadensbegrenzung - senkt den Verlust und die Folgeschäden nach einem gelungenen Angriff, nicht dessen Wahrscheinlichkeit",
    "ui.effect.deterrent": "verringert die Zahl der unternommenen Versuche",
    "ui.effect.avoidance": "entfernt die Exposition, sodass der Akteur seltener in Kontakt kommt",
    "ui.taxonomy.in-use-here": "In Nutzung: {0} {1}. Dort zuerst entfernen.",
    "ui.taxonomy.and-n-more.one": "und {0} weiteren",
    "ui.taxonomy.and-n-more.many": "und {0} weitere",
    "ui.mitigation.tactic-defended": "{0}: zu {1} % verteidigt - klicken, um die Rechnung zu sehen",
    "ui.mitigation.outcome-of-an-attempt": "Ausgang eines Angriffsversuchs, aus derselben Traversierung wie die Risikozahlen",
    "ui.mitigation.ring-label": "{0} % der Versuche gestoppt - {1} % abgewehrt, {2} % auf frischer Tat gefasst, {3} % erreichen das Ziel",
    "ui.mitigation.attempts-stopped": "Versuche gestoppt",
    "ui.mitigation.blocked": "abgewehrt",
    "ui.mitigation.detected-in-time": "rechtzeitig erkannt",
    "ui.mitigation.reaches-the-objective": "erreicht das Ziel",
    "ui.mitigation.undefended": "unverteidigt",
    "ui.mitigation.fully-defended": "vollständig verteidigt",
    "ui.mitigation.click-a-tile": "eine Kachel anklicken für die Rechnung",
    "ui.mitigation.attempts-this-chain-stops": "Versuche, die diese Kette stoppt",
    "ui.entitysection.disabled-with-it.one": "Wird mit ausgeschlossen ({0})",
    "ui.entitysection.disabled-with-it.many": "Werden mit ausgeschlossen ({0})",
    "ui.entitysection.in-use-by.one": "Wird derzeit von {0} Datensatz benötigt",
    "ui.entitysection.in-use-by.many": "Wird derzeit von {0} Datensätzen benötigt",
    "ui.entitysection.none-left": "keine mehr",
    "ui.entitysection.disable": "Ausschließen",
    "ui.entitysection.enable": "Einbeziehen",
    "ui.entitysection.log-disabled": "Ausgeschlossen",
    "ui.entitysection.log-enabled": "Einbezogen",
    "ui.entitysection.also-affected.one": "Ebenfalls betroffen ({0})",
    "ui.entitysection.also-affected.many": "Ebenfalls betroffen ({0})",
    "ui.entitysection.deleted-with-it.one": "Wird mitgelöscht ({0}) — das lässt sich nicht rückgängig machen",
    "ui.entitysection.deleted-with-it.many": "Werden mitgelöscht ({0}) — das lässt sich nicht rückgängig machen",
    "ui.entitysection.loses-a-reference.one": "Verliert einen Verweis darauf ({0})",
    "ui.entitysection.loses-a-reference.many": "Verlieren einen Verweis darauf ({0})",
    "ui.entitysection.n-more.one": "+{0} weiterer",
    "ui.entitysection.n-more.many": "+{0} weitere",
    "ui.assetheatmap.collapse": "Zuklappen",
    "ui.assetheatmap.expand-dependencies": "Abhängigkeiten aufklappen",
    "ui.history.imported": "importiert",
    "ui.history.updated": "geändert",
    "ui.history.integrity-verified": "Integrität bestätigt",
    "ui.history.log-altered": "Protokoll verändert",
    "ui.history.changed-outside": "außerhalb der Anwendung geändert",
    "ui.history.not-in-the-log": "nicht im Protokoll",
    "ui.history.hash-chain-intact": "Hash-Kette unversehrt und zu den Daten passend",
    "ui.checks.sev-high": "Hoch",
    "ui.checks.sev-medium": "Mittel",
    "ui.checks.sev-low": "Gering",
    "ui.datamenu.data": "Daten",
    "ui.datamenu.export": "Export",
    "ui.datamenu.this-study-paren": "(diese Studie)",
    "ui.datamenu.everything-paren": "(alles)",
    "ui.datamenu.this-study": "Diese Studie",
    "ui.datamenu.studies": "Studien",
    "ui.datamenu.hint-portable": "Taxonomie + Daten + Dokumente + Einstellungen",
    "ui.datamenu.hint-data-only": "nur Daten",
    "ui.datamenu.hint-schema-only": "nur Schema",
    "ui.datamenu.hint-file-or-paste": "Datei oder Einfügen",
    "ui.datamenu.encrypt-to-named-keys": "Für die benannten Schlüssel verschlüsseln",
    "ui.datamenu.no-keys-named": "Noch kein Schlüssel benannt - im Siegel-Bereich des Verlaufs einen benennen",
    "ui.study.export-import": "Export / Import",
    "ui.entitymodal.your-name": "Ihr Name",
    "ui.entitymodal.why-this-change": "Grund der Änderung",
    "ui.extraction.optional": "optional",
    "ui.ui.open": "Öffnen",
    "ui.mitigation.hide-per-scenario": "Je Szenario ausblenden",
    "ui.mitigation.break-down-per-scenario": "Nach Szenario aufschlüsseln",
    "ui.catalogimport.f-ref-id": "Referenz-ID",
    "ui.catalogimport.f-title": "Titel",
    "ui.catalogimport.f-category": "Kategorie",
    "ui.catalogimport.f-description": "Beschreibung",

    // ── graph ──
    "ui.graph.search-entities": "Entitäten suchen…",
    "ui.graph.no-matches": "Keine Treffer.",
    "ui.graph.nothing-to-show-yet": "Noch nichts zu zeigen",
    "ui.graph.add-entities-in-the": "Legen Sie Entitäten in den Workshops an — der Graph wächst mit ihnen.",
    "ui.graph.reset-positions": "Positionen zurücksetzen",
    "ui.graph.put-every-node-back": "Jeden Knoten dorthin zurücksetzen, wo das Layout ihn hinlegt",
    "ui.graph.clear-extra": "Zusätzliche entfernen",

    // ── kill chain ──
    "ui.killchainlane.step": "Schritt",
    "ui.killchainlane.unassigned": "Nicht zugeordnet",
    "ui.killchainlane.drag-to-a-tactic": "Auf eine Tactic-Kachel ziehen · zum Bearbeiten klicken",
    "ui.killchainmitigation.kill-chain-mitigation": "Kill-chain-Mitigation",
    "ui.killchainmitigation.mitigation": "Minderung",
    "ui.killchainmitigation.operational-scenario": "Operatives Szenario",
    "ui.killchainmitigation.no-operational-scenarios-yet": "Noch keine Operational scenarios.",
    "ui.killchainmitigation.no-kill-chain-steps": "Noch keine Kill-chain-Schritte in diesem Szenario — legen Sie sie unter Operational Scenarios an.",
    "ui.mitigationcharts.chain-defence": "Verteidigung der Kette",
    "ui.mitigationcharts.ttp-tactic-defence": "Verteidigung nach TTP-Tactic",
    "ui.mitigationcharts.defense-in-depth-per": "Defense in depth — je Kill-chain-Schritt",
    "ui.mitigationcharts.all-scenarios": "Alle Szenarien",
    "ui.mitigationcharts.no-tactics-assigned-to": "Den Kill-chain-Schritten sind noch keine Tactics zugeordnet.",
    "ui.mitigationcharts.corrective-deterrent-and-avoidance": "Corrective-, deterrent- und avoidance-Maßnahmen werden hier nicht gezählt",
    "ui.mitigationcharts.a-second-measure-on": "Eine zweite Maßnahme am selben Schritt schließt einen Teil dessen, was die erste offen ließ. Jede zählt danach, wie weit sie umgesetzt ist und wo sie greift.",
    "ui.mitigationcharts.this-measures-how-consistently": "Das misst, wie durchgängig die Schritte einer Tactic verteidigt sind, nicht wie wahrscheinlich ein Angriff scheitert — das hängt auch davon ab, wo er ansetzt.",
    "ui.mitigationcharts.close": "Schließen",

    // ── modelling ──
    "ui.modelling.class": "Klasse",
    "ui.modelling.requirements": "Anforderungen",
    "ui.modelling.inherited": "Geerbt",
    "ui.modelling.derived-from-the-catalogue": "Aus dem Katalog abgeleitet",

    // ── catalogues ──
    "ui.catalogadd.choose-from-a-catalog": "Aus einem Katalog wählen",
    "ui.catalogadd.create-custom": "Eigenen anlegen…",
    "ui.catalogadd.documents": "Dokumente",
    "ui.catalogadd.import-elsewhere": "Eine Framework-Datei importieren Sie unter {0}.",
    "ui.catalogadd.close": "Schließen",
    "ui.catalogimport.import-a-framework-catalog": "Framework / Katalog importieren",
    "ui.catalogimport.documents-semi-deterministic-import": "Dokumente · halbdeterministischer Import",
    "ui.catalogimport.import-as": "Importieren als",
    "ui.catalogimport.framework-name-optional": "Name des Frameworks (optional)",
    "ui.catalogimport.paste-a-table-csv": "Fügen Sie eine Tabelle (CSV/TSV) oder JSON ein, oder wählen Sie eine Datei — CSV, JSON, Text, oder ein PDF- oder Word-Dokument, dessen Text zuerst extrahiert wird. Werte werden gelesen",
    "ui.catalogimport.choose-file": "Datei wählen…",
    "ui.catalogimport.parse": "Einlesen",
    "ui.catalogimport.download-template": "Vorlage herunterladen",
    "ui.catalogimport.sheet": "Blatt",
    "ui.catalogimport.map-columns": "Spalten zuordnen",
    "ui.catalogimport.joined-in-column-order": "In Spaltenreihenfolge zusammengefügt. Ein Teil, der nur wiederholt, was schon steht, bleibt weg.",
    "ui.catalogimport.sections-found": "Gefundene Abschnitte",
    "ui.catalogimport.select-what-to-add": "Wählen, was hinzukommt",
    "ui.catalogimport.vocabularies-this-catalogue-defines": "Vokabulare, die dieser Katalog festlegt",
    "ui.catalogimport.the-vocabularies-this-catalogue": "Die Vokabulare dieses Katalogs sind bereits die, die dieser Build anbietet — nichts nachzuziehen.",
    "ui.catalogimport.extend": "Erweitern",
    "ui.catalogimport.replace": "Ersetzen",
    "ui.catalogimport.from-the-publisher": "Vom Herausgeber.",
    "ui.catalogimport.the-catalogue-is-fetched": "Der Katalog wird geholt, wenn Sie dies drücken, und sonst nicht — die Anwendung fragt von sich aus nichts an und funktioniert ohne Netz.",
    "ui.catalogimport.close": "Schließen",

    // ── import and verification ──
    "ui.import.source": "Quelle",
    "ui.import.choose-file": "Datei wählen…",
    "ui.import.paste-json-yaml": "JSON / YAML einfügen",
    "ui.import.paste-a-bundle-study": "Fügen Sie hier ein Bundle, Studiendaten oder eine Taxonomy ein…",
    "ui.import.data-json-yaml-auto": "Daten · JSON / YAML (automatisch erkannt)",
    "ui.import.preview-pasted": "Eingefügtes ansehen →",
    "ui.import.preview-a-demo-revision": "Eine Beispiel-Revision ansehen",
    "ui.import.see-the-diff-without": "Den Unterschied sehen, ohne eine Datei zu bearbeiten",
    "ui.import.choose-a-source-to": "Wählen Sie eine Quelle, um die Änderungen zuerst anzusehen.",
    "ui.import.no-differences": "Keine Unterschiede.",
    "ui.import.no-study-data-in": "Keine Studiendaten in dieser Datei (nur Taxonomy/Einstellungen).",
    "ui.import.not-sealed": "Nicht versiegelt.",
    "ui.import.nothing-in-this-file": "Nichts in dieser Datei sagt, wer sie erzeugt hat; ihr Änderungsprotokoll lässt sich nur gegen sich selbst prüfen.",
    "ui.import.verified": "Verifiziert",
    "ui.import.not-verified": "Nicht verifiziert",
    "ui.import.signature-valid-sender-unconfirmed": "Signatur gültig, Absender unbestätigt",
    "ui.import.hold-the-sender-apos": "Haben Sie den öffentlichen Schlüssel des Absenders? Prüfen Sie ihn gegen dieses Seal.",
    "ui.import.check-against-a-key": "Gegen eine Schlüsseldatei prüfen…",
    "ui.import.close": "Schließen",

    // ── taxonomy editor ──
    "ui.taxonomy.taxonomy": "Taxonomie",
    "ui.taxonomy.meta-schema": "Meta-Schema",
    "ui.taxonomy.entity-type": "Entitätstyp",
    "ui.taxonomy.new-entity-type": "Neuer Entity type",
    "ui.taxonomy.delete-entity-type": "Entity type löschen",
    "ui.taxonomy.select-or-create-an": "Wählen oder legen Sie einen Entity type an.",
    "ui.taxonomy.group": "Gruppe",
    "ui.taxonomy.new-group-tab": "Neue Group (Reiter)",
    "ui.taxonomy.label": "Bezeichnung",
    "ui.taxonomy.plural": "Plural",
    "ui.taxonomy.field": "Feld",
    "ui.taxonomy.fields": "Felder",
    "ui.taxonomy.remove-field": "Field entfernen",
    "ui.taxonomy.accent-color-css": "Akzentfarbe (CSS)",
    "ui.taxonomy.reset-default": "Auf Vorgabe zurücksetzen",
    "ui.taxonomy.create": "Anlegen",
    "ui.taxonomy.cancel": "Abbrechen",

    "ui.ui.close": "Schließen",

    // ── counted phrases: two forms, because German has no suffix rule ──
    "ui.attackpaths.chokepoints.one": "{0} Choke point", "ui.attackpaths.chokepoints.many": "{0} Choke points",
    "ui.changehistory.links.one": "{0} Verknüpfung", "ui.changehistory.links.many": "{0} Verknüpfungen",
    "ui.changehistory.changes.one": "{0} Änderung", "ui.changehistory.changes.many": "{0} Änderungen",
    "ui.entitysection.others.one": "{0} weiterer", "ui.entitysection.others.many": "{0} weitere",
    "ui.entitysection.disabledWith.one": "Zurückgestellt mit {0} abhängigen Datensatz",
    "ui.entitysection.disabledWith.many": "Zurückgestellt mit {0} abhängigen Datensätzen",
    "ui.factortrace.steps.one": "{0} Schritt", "ui.factortrace.steps.many": "{0} Schritte",
    "ui.graph.relationships.one": "{0} Beziehung", "ui.graph.relationships.many": "{0} Beziehungen",
    "ui.import.links.one": "{0} Verknüpfung", "ui.import.links.many": "{0} Verknüpfungen",
    "ui.import.records.one": "{0} Datensatz", "ui.import.records.many": "{0} Datensätze",
    "ui.mitigationcharts.steps.one": "{0} Schritt", "ui.mitigationcharts.steps.many": "{0} Schritte",
    "ui.seal.changes.one": "{0} Änderung", "ui.seal.changes.many": "{0} Änderungen",
    // `kind` is the target's own name, which stays as the taxonomy has it.
    "ui.catalogimport.added.one": "{0} hinzugefügt", "ui.catalogimport.added.many": "{0} hinzugefügt",
    "ui.audit.records.one": "{0} Datensatz", "ui.audit.records.many": "{0} Datensätze",
    "report.furtherScenarios.one": "{0} weiteres Szenario", "report.furtherScenarios.many": "{0} weitere Szenarien",
    "report.editors.one": "{0} Bearbeiter", "report.editors.many": "{0} Bearbeiter",
    "report.steps.one": "{0} Schritt", "report.steps.many": "{0} Schritte",
    "quant.gatedSteps.one": "{0} Schritt", "quant.gatedSteps.many": "{0} Schritte",
    "quant.watchedSteps.one": "{0} Schritt", "quant.watchedSteps.many": "{0} Schritte",

    // ── completeness checks: engine text, translated once for every product ──
"check.uncovered-steps.hint": "Fügen Sie eine Security measure hinzu, die jeden offenen Schritt abdeckt, oder nehmen Sie die Lücke ausdrücklich in Kauf.",
    "check.empty-opscenario.hint": "Modellieren Sie die Kill chain (Schritte + Tactics) für jedes Operational scenario.",
    "check.unrefined-strategic.hint": "Verfeinern Sie jedes Strategic scenario zu mindestens einem Operational scenario mit Kill chain.",
    "check.untreated-risk.hint": "Legen Sie eine Risikobehandlung fest (Reduce / Accept / Share / Avoid) samt Restrisikoniveau.",
    "check.asset-no-feared.hint": "Benennen Sie zu jedem Business asset, was schiefgehen könnte (ein Feared event).",
    "check.feared-unused.hint": "Verbinden Sie jedes Feared event mit dem Szenario oder den Szenarien, die es auslösen würden.",
    "check.orphan-support.hint": "Verknüpfen Sie jedes Supporting asset mit dem Business asset, das es trägt.",
    "check.req-uncovered.hint": "Ordnen Sie jedem Requirement eine Security measure zu, oder setzen Sie es außerhalb des Geltungsbereichs.",
    "check.measure-dangling.hint": "Richten Sie jede Maßnahme auf die Schritte, die sie abdeckt, die Assets, die sie schützt, oder die Requirements, die sie erfüllt.",
    "check.measure-unclassified.hint": "Setzen Sie den Maßnahmentyp. Die Quantification leitet die Wirkung eines Controls daraus ab — ein corrective Control mindert den Schaden, ein detective kann die Kette brechen.",
    "check.damage-control-only.hint": "An diesen Schritten hängt nichts, was blockiert oder entdeckt — sie kosten einen Angreifer nichts.",
    "check.step-no-tactic.hint": "Ein Schritt ohne Tactic fehlt in der Tactic-Verteidigungsansicht. Setzen Sie die Tactic, damit der Schritt zählt.",
    "check.chain-nothing-stops.hint": "Auf diesen Ketten hält nichts einen Versuch auf — jeder Angreifer, der beginnt, kommt durch.",
    "check.chain-detection-only.hint": "Diese Ketten werden allein durch Detection verteidigt; entdeckt zu werden hält allein noch niemanden auf.",
    "check.detection-no-response.hint": "Diese Ketten tragen detective Maßnahmen, aber keine corrective — das Modell schreibt ihnen daher fast keine Reaktionsfähigkeit zu.",
    "check.chain-no-prerequisites.hint": "Kein Schritt dieser Ketten nennt seine Voraussetzungen, die Kette wird also als Reihenfolge gelesen. Setzen Sie „preceded by“, wo ein Schritt wirklich auf einem anderen aufbaut.",
    "check.reduce-without-measures.hint": "Die Entscheidung lautet auf Reduktion, aber an keinem Schritt der Ketten hinter diesem Risiko hängt eine Maßnahme. Entweder die Maßnahme anhängen oder die Entscheidung ändern.",
    "check.actor-no-category.hint": "Die Category bestimmt, wie oft ein Akteur dieser Art überhaupt angreift — eine kriminelle Gruppe und ein staatlicher Akteur unterscheiden sich um mehr als eine Größenordnung.",
    "check.actor-no-objective.hint": "Erst ein Objective, das an einem Business asset hängt, sagt dem Modell, dass dieser Akteur gerade etwas von Ihnen will.",
    "check.entry-no-technique.hint": "Die Einstiegs-Technique entscheidet zweierlei zugleich: wie oft der Akteur überhaupt in Kontakt kommt, und wie viel Können der erste Fuß in der Tür verlangt.",
    "check.source-unused.hint": "Bauen Sie entweder ein Szenario für die Risk source, oder entfernen Sie sie.",
    "check.source-unused.title": "Risk sources, die in keinem Szenario benutzt werden",
    "check.uncovered-steps.title": "Kill-chain-Schritte ohne Security measure",
    "check.empty-opscenario.title": "Operational scenarios ohne Kill-chain-Schritte",
    "check.unrefined-strategic.title": "Strategic scenarios ohne Operational scenario",
    "check.untreated-risk.title": "Risiken ohne Behandlungsentscheidung",
    "check.asset-no-feared.title": "Business assets ohne Feared event",
    "check.feared-unused.title": "Feared events, die mit keinem Strategic scenario verknüpft sind",
    "check.orphan-support.title": "Supporting assets ohne Verknüpfung zu einem Business asset",
    "check.req-uncovered.title": "Requirements, die keine Maßnahme erfüllt",
    "check.measure-dangling.title": "Security measures ohne Ziel",
    "check.measure-unclassified.title": "Security measures ohne Effect class",
    "check.damage-control-only.title": "Kill-chain-Schritte, an denen nichts blockiert oder entdeckt",
    "check.step-no-tactic.title": "Kill-chain-Schritte ohne Tactic",
    "check.chain-nothing-stops.title": "Kill chains, die nichts blockiert oder entdeckt",
    "check.chain-detection-only.title": "Kill chains, die allein durch Detection verteidigt sind",
    "check.detection-no-response.title": "Überwachte Ketten ohne Möglichkeit zu reagieren",
    "check.chain-no-prerequisites.title": "Kill chains, die als gerade Linie modelliert sind",
    "check.reduce-without-measures.title": "Risiken als „Reduce“ behandelt, ohne dass etwas sie reduziert",
    "check.actor-no-category.title": "Risk sources ohne Category",
    "check.actor-no-objective.title": "Risk sources ohne Target objective",
    "check.entry-no-technique.title": "Ketten, deren erster Schritt keine Technique nennt",
    
    "ui.datamenu.each-of-them-opens": "Jeder von ihnen öffnet sie mit seinem eigenen Schlüssel. Die Liste der Empfänger ist in der Datei lesbar — daran erkennt man, ob sie an jemanden ging, den man nicht erwartet hat.",
  },
};
